---
instances:
- https://rss.shab.fun/
- https://vercel.getrss2021.xyz/
- https://rsshub.rssforever.com/
- http://getrss2021.xyz:1200/
- https://rsshub.app/
routes:
- title: æˆ‘çš„github
  path: github/repos/Ikaros-521
- title: æˆ‘çš„æ¨ç‰¹
  path: twitter/user/love_ikaros1314
- title: å¤§é…±çš„ æ¨ç‰¹
  path: twitter/user/shizuku_mayoi
- title: ç¾½æœˆçš„ æ¨ç‰¹
  path: twitter/user/chii_nemui
- title: è‰è‰ä¸çš„ æ¨ç‰¹
  path: twitter/user/amaririsu_ch
- title: AgeåŠ¨æ¼« æœ€è¿‘æ›´æ–°
  path: agefans/update
- title: çŒ«éŸ³ã™ãš ytbé¢‘é“
  path: youtube/channel/UCpEESTSpGHDgKTDJfS57Zkg
- title: é­”æ³•å¹¼å¥³ãˆã† ytbé¢‘é“
  path: youtube/channel/UCIm7s5zSSoTIDbtxrG2CvQA
- title: ã²ã‚‡ãŒã‚ˆã‚ğŸ¦˜Hyogayome ytbé¢‘é“
  path: youtube/channel/UC_ulAd_3TQIlLRAo5zNhnoQ
- title: é»‘ç”·é‚±æ¯”ç‰¹ ytbé¢‘é“
  path: youtube/channel/UC4GZ1dNQKWWFDQ4IWl4DezA
# baseUrl: https://raw.githubusercontent.com/wdssmq/proxy_rsshub/main # The Base Url Of xml folder
